App\Entity\City:
    properties:
        longitude:
             - Range:
                min: -180
                max: 180
                groups: [new, edit]
        latitude:
             - Range:
                min: -90
                max: 90
                groups: [new, edit]


App\Entity\Forecast:
    properties:
        temperature:
             - Range:
                min: -100
                max: 100
                groups: [new, edit]
        humidity:
             - Range:
                min: 0
                max: 100
                groups: [new, edit]
        rain:
             - Range:
                min: 0
                max: 100
                groups: [new, edit]
